version: "3.1"
services:

  financemanagerapp:
    build:
      context: .
      dockerfile: ./Dockerfile-financemanagerapp
    image: qopuir/financemanagerapp:1.1.0
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - /c/work/repos/financemanager/wksp/import:/financemanager/import
      - /c/work/repos/financemanager/wksp/shared/dbfiles:/financemanager/dbfiles
    networks:
      - financemanagerapp

networks:
  financemanagerapp:
