version: "3.1"
services:

  firefox-node:
    image: selenium/node-firefox-debug:3.141.59-20201119
    container_name: firefox-node
    shm_size: 2g
    depends_on:
      - selenium-hub
    environment:
      - VNC_NO_PASSWORD=1
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=24
      - SCREEN_DPI=96
    ports:
      - 6901:5900
    networks:
      - bankscrapper

  selenium-hub:
    image: selenium/hub:3.141.59-20201119
    container_name: selenium-hub
    ports:
      - 4444:4444
    networks:
      - bankscrapper

  bankscrapper:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_NAME: bankscrapper
        BUNDLE_VERSION: 1.0.0-SNAPSHOT
    image: qopuir/bankscrapper:1.0.0-SNAPSHOT
    ports:
      - 5005:5005
    depends_on:
      - selenium-hub
      - firefox-node
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - /c/work/repos/financemanager/wksp/shared/dbfiles:/financemanager/dbfiles
      - /c/work/repos/financemanager/wksp/shared/credentials:/financemanager/credentials
      - /c/work/repos/financemanager/wksp/bankscrapper:/financemanager/bankscrapper
    networks:
      - bankscrapper
    entrypoint: ["/financemanager/entrypoint_debug.sh"]
    command: ["--sync-type", "PAST_ONE_MONTH", "--bank-credential", "/financemanager/credentials/kb_credentials", "--encryption-password", "/financemanager/credentials/encryption_password"]

networks:
  bankscrapper:
