logging:
  level:
    com.diegocastroviadero: INFO

financemanagerapp:
  cache:
    clean-interval: 1800000 # 30 minutes
  security:
    requires-https: true
    incorrect-logins-to-block-ip: 5
  persistence:
    dbfiles:
      base-path: /financemanager/dbfiles