logging:
  level:
    root: WARN
    org.atmosphere: WARN
    com.diegocastroviadero: DEBUG

server:
  port: ${PORT:8080}
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 5s

vaadin:
  compabibilitymode: false

financemanagerapp:
  build:
    version: @project.version@
    timestamp: @maven.build.timestamp@
  cache:
    clean-interval: 60000
    expiration-millis: 60000
  import:
    base-path: wksp/import
    delete-after-import: false
  persistence:
    dbfiles:
      base-path: wksp/shared/dbfiles