logging:
  level:
    root: WARN
    org.atmosphere: WARN
    com.diegocastroviadero: INFO

financemanagerapp:
  password-cache-expiration-millis: 600000
  import:
    base-path: /financemanager/import
    deleteA-after-import: true
  persistence:
    dbfiles:
      base-path: /financemanager/dbfiles